---
- include:              '../tasks/template_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/symlinks.yml'
- include:              '../tasks/restart_services.yml'
  when:                 template_files_result.changed or install_files_result.changed or symlinks_result.changed
